---
- name: Deploy Mavi Web App
  hosts: webservers
  become: yes
  vars:
    app_repo_url: "https://github.com/nistarg/mavi.git"
    app_directory: "/var/www/mavi"
    app_branch: "main"
    node_version: "16.x"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name:
          - curl
          - gnupg
        state: present

    - name: Add NodeSource repository for Node.js
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }} | bash -
      args:
        creates: /usr/bin/node

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install build-essential for compiling native addons
      apt:
        name: build-essential
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Clone the repository
      git:
        repo: "{{ app_repo_url }}"
        dest: "{{ app_directory }}"
        version: "{{ app_branch }}"
        force: yes

    - name: Install npm dependencies
      npm:
        path: "{{ app_directory }}"
        state: present

    - name: Build the application
      npm:
        path: "{{ app_directory }}"
        executable: "npm"
        args:
          - run
          - build

    - name: Configure Nginx to serve the app
      template:
        src: "nginx_config.j2"
        dest: "/etc/nginx/sites-available/mavi"
      notify:
        - restart nginx

    - name: Enable site in Nginx
      command:
        cmd: "ln -s /etc/nginx/sites-available/mavi /etc/nginx/sites-enabled/"
        creates: "/etc/nginx/sites-enabled/mavi"

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
